// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PropertyManagement.API.Data;

#nullable disable

namespace PropertyManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709000000_AddMaintenanceClaims")]
    partial class AddMaintenanceClaims
    {
    }
}
